apiVersion: v1
kind: ConfigMap
metadata:
  name: modernapi-config
  namespace: modernapi
  labels:
    app.kubernetes.io/name: modernapi
    app.kubernetes.io/component: config
data:
  # Application Configuration
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  
  # JWT Configuration  
  JWT_ISSUER: "ModernAPI"
  JWT_AUDIENCE: "ModernAPI.Users"
  JWT_ACCESS_TOKEN_EXPIRY_MINUTES: "15"
  JWT_REFRESH_TOKEN_EXPIRY_DAYS: "7"
  
  # Logging Configuration
  LOG_LEVEL: "Warning"
  ENABLE_DETAILED_ERRORS: "false"
  ENABLE_SENSITIVE_DATA_LOGGING: "false"
  
  # OpenTelemetry Configuration
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
  OTEL_SERVICE_NAME: "ModernAPI"
  OTEL_RESOURCE_ATTRIBUTES: "environment=production"
  
  # Monitoring Configuration
  SEQ_URL: "http://seq:5341"
  
  # Feature Flags
  ENABLE_SWAGGER: "false"
  
  # CORS Configuration
  CORS_ORIGINS: "https://app.yourdomain.com,https://admin.yourdomain.com"