services:
  postgres:
    image: postgres:16
    container_name: modernapi-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-modernapi}
      POSTGRES_USER: ${POSTGRES_USER:-modernapi_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dev_password_123}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-modernapi_user} -d ${POSTGRES_DB:-modernapi}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: modernapi-redis
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-dev_redis_password}
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "requirepass $$REDIS_PASSWORD" > /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "maxmemory 256mb" >> /usr/local/etc/redis/redis.conf &&
        echo "maxmemory-policy allkeys-lru" >> /usr/local/etc/redis/redis.conf &&
        redis-server /usr/local/etc/redis/redis.conf
      '
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local