name: 🔒 Security Issue
description: Report a security vulnerability (PRIVATE - will be handled confidentially)
title: "[SECURITY] "
labels: ["security", "private"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: This template is for security vulnerabilities. Please do NOT include sensitive details in public issues.
        
        For serious security vulnerabilities, consider using GitHub's private vulnerability reporting or contact the security team directly.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Critical - Remote code execution, data breach, authentication bypass
        - High - Privilege escalation, injection attacks, significant data exposure
        - Medium - Information disclosure, CSRF, weak authentication
        - Low - Minor information leakage, configuration issues
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Vulnerability Type
      description: What type of security issue is this?
      options:
        - Authentication Bypass
        - Authorization Issues
        - SQL Injection
        - Cross-Site Scripting (XSS)
        - Cross-Site Request Forgery (CSRF)
        - Remote Code Execution (RCE)
        - Local File Inclusion (LFI)
        - Information Disclosure
        - Insecure Configuration
        - Cryptographic Issues
        - Dependency Vulnerability
        - API Security Issue
        - Container/Docker Security
        - Infrastructure Security
        - Other
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Security Issue Summary
      description: Brief, non-sensitive description of the vulnerability
      placeholder: "High-level description without sensitive details..."
    validations:
      required: true

  - type: dropdown
    id: affected-component
    attributes:
      label: Affected Component
      description: Which part of the system is affected?
      options:
        - Authentication System
        - API Endpoints
        - Database Layer
        - User Management
        - File Upload/Storage
        - External Integrations
        - Docker/Container
        - CI/CD Pipeline
        - Configuration
        - Dependencies
        - Multiple Components
        - Unknown
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker potentially achieve?
      placeholder: |
        - Data that could be accessed
        - Systems that could be compromised
        - User accounts that could be affected
        - Potential business impact

  - type: dropdown
    id: exploitability
    attributes:
      label: Exploitability
      description: How easy is it to exploit this vulnerability?
      options:
        - Easy - No authentication required, simple to exploit
        - Medium - Some authentication or specific conditions required
        - Hard - Requires deep system knowledge or complex conditions
        - Unknown - Needs investigation
    validations:
      required: true

  - type: checkboxes
    id: affected-environments
    attributes:
      label: Affected Environments
      description: Which environments are vulnerable?
      options:
        - label: Production
        - label: Staging
        - label: Development
        - label: All environments
        - label: Unknown

  - type: input
    id: versions
    attributes:
      label: Affected Versions
      description: Which versions are affected?
      placeholder: "v1.2.0 - v1.3.1, or All versions"

  - type: textarea
    id: discovery
    attributes:
      label: Discovery Method
      description: How was this vulnerability discovered?
      placeholder: |
        - Security scan/audit
        - Penetration testing
        - Code review
        - Bug bounty
        - User report
        - Automated security tools

  - type: textarea
    id: reproduction-safe
    attributes:
      label: Safe Reproduction Steps
      description: General steps to reproduce (without sensitive details or exploits)
      placeholder: |
        Please provide non-sensitive reproduction steps.
        DO NOT include actual exploit code or sensitive system information.

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      options:
        - label: I am reporting this through responsible disclosure
          required: true
        - label: I have not shared this vulnerability publicly
          required: true
        - label: I will wait for a fix before public disclosure
          required: true

  - type: dropdown
    id: public-disclosure
    attributes:
      label: Public Disclosure Timeline
      description: When is it acceptable to publicly disclose this?
      options:
        - After fix is deployed to production
        - After 90 days regardless of fix status
        - After 180 days regardless of fix status
        - Never (prefer to keep private)
        - Coordinate with security team
    validations:
      required: true

  - type: textarea
    id: contact
    attributes:
      label: Contact Information
      description: How should the security team contact you for follow-up?
      placeholder: |
        Email: your-email@example.com
        Encrypted communication preference: [if any]
        Best time to contact: [timezone/hours]

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any additional non-sensitive context
      placeholder: |
        - Related security research
        - Similar vulnerabilities in other systems
        - Suggested mitigation approaches
        - References to security standards

  - type: markdown
    attributes:
      value: |
        ---
        
        ## Next Steps
        
        1. **Security team will acknowledge** this report within 24-48 hours
        2. **Initial assessment** will be completed within 1 week
        3. **Fix timeline** will be communicated based on severity
        4. **You will be kept updated** throughout the remediation process
        5. **Credit will be given** (if desired) once the issue is resolved
        
        Thank you for helping keep ModernAPI secure! 🔒